#!/bin/sh

ruby -e '`gem list -i \"^git-smart$\"`.chomp=="true" or `gem install git-smart`'

if [ ! -e $HOME/.vim/bundle/Vundle.vim ]; then
  git clone https://github.com/gmarik/Vundle.vim.git $HOME/.vim/bundle/Vundle.vim
fi

vim -u $HOME/.vimrc.bundles +PluginInstall +qa
